version: '3.7'

services:
  mysql:
    hostname: mysql
    build:
      context: .
    environment:
      - MYSQL_PASSWORD
      - HEALTHCHECK_PASSWORD
    volumes:
      - ./data:/var/lib/mysql
    ports:
      #- 172.31.0.1:3306:3306
      - 3306:3306
    logging:
      driver: json-file
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "/usr/bin/mysql --user=docker-healthcheck --host=127.0.0.1 --password=$HEALTHCHECK_PASSWORD --batch --silent -e 'select 1;' > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

