#!/usr/bin/env bash

usage() {
  echo "Usage: $0 <Backup file from mariadb-backup to restore>"
  exit 1
}

BACKUP_FILE="$1"
if [ -z "$BACKUP_FILE" ]; then
  usage
fi

. ./.env

TARGET_DIR=${TARGET_DIR:-"./mariadb-backup"}
GPG_KEYID=${GPG_KEYID:-""}
TMPNAME="${TARGET_DIR}/${BACKUP_FILE}"

if [ ! -O "${TMPNAME}" ]; then
  echo "Cannot access ${TMPNAME}"
  exit 1
fi

PATH=/bin:/usr/bin
export PATH

ID=$(docker ps --filter "label=MYSQL=mariadb" --format "{{.ID}}")
if [ -z "$ID" ]; then
  echo "MariaDB container not found"
  exit 1
fi

echo "$BACKUP_FILE" | grep '\.gpg$' > /dev/null
if [ $? -eq 0 ]; then
  XZ_FILE=$(basename "${BACKUP_FILE}" .gpg).xz
  gpg -d "${TMPNAME}" > "${TARGET_DIR}/${XZ_FILE}"
else
  XZ_FILE="${BACKUP_FILE}"
fi

cd "${TARGET_DIR}"
SQL_FILE=$(tar xvf "${XZ_FILE}")
cd ..

docker exec -i $ID mariadb < "${TARGET_DIR}/${SQL_FILE}"
if [ $? -ne 0 ]; then
  echo "Fatal: mariadb < ${TARGET_DIR}/${SQL_FILE} failed"
  exit 2
fi

# clean up
cd "$TARGET_DIR" || exit 1
rm -f "${XZ_FILE}" "${SQL_FILE}"

